Zendesk Integration
restackio/integrations-typescript pull request #28
Opened 2024-10-19 02:18 UTC by notmessenger

This package provides an integration for Zendesk with Restack, allowing:

- the [creation of tickets](https://developer.zendesk.com/documentation/ticketing/managing-tickets/creating-and-updating-tickets/)

Addresses https://github.com/restackio/integrations-typescript/issues/21

2024-10-19 02:19 UTC, notmessenger commented
@aboutphilippe

2024-11-05 12:49 UTC, justrdk requested changes

2024-11-05 12:49 UTC, justrdk commented on zendesk/functions/createTicket.ts
> +    if (assignee_email) {
I think instead of having these if conditions to conditionally set the property, you could do this above at same time you define the variable:

```typescript
const ticket: Record<string, boolean | number | Array<number> | object | string | Array<string> | undefined | Array<CustomField> | Priority | Status | TicketComment> = {
   ...(assignee_email && {assignee_email})
   ...(assignee_id && {assignee_id})
  // rest of fields this way as well
}

2024-11-10 21:24 UTC, justrdk approved these changes

2024-11-10 21:24 UTC, merged