Add AWS Polly integration
restackio/integrations-typescript pull request #43
Opened 2024-10-28 20:07 UTC by Thorleon

It's the equivalent of Azure Speech integration, for the AWS-based customers. I also have included all available options from the SDK.

2024-11-05 10:50 UTC, justrdk requested changes

2024-11-05 10:50 UTC, justrdk commented on aws-polly/functions/speech.ts
> +    throw new Error(`AWS Polly error ${error}`);
you can also throw a non retryable function failure here. There won't be a need for the workflow that calls this function to retry it in case there is an error in this scenario.

2024-11-05 10:50 UTC, justrdk commented on aws-polly/functions/speech.ts
> +    throw new Error("No audio stream in AWS Polly result");
same here.

2024-11-06 10:23 UTC, martinibach commented
@Thorleon we are deprecating integrations based on user feedback indicating a preference for creating custom functions. Users have requested high-quality example functions for specific providers that they can easily copy and paste, rather than importing integrations from a package. Could you please create a PR in the [examples-typescript](https://github.com/restackio/examples-typescript/tree/main/examples) repository with straightforward example workflows for AWS Polly as well and also take @justrdk feedback into account, please?

2024-11-06 10:23 UTC, closed without merging